server:
  port: 8080    #HTTPS????????443?????????????????????
#  ssl:
#    key-store-password: 5kyarrvw    #??jks-password.txt???????
#    key-store-type: JKS #JKS??????????PFX???????????PKCS12?
#    key-store: classpath:eqmaster.redamancyxun.fun.jks   #??????????????domain_name.jks?
  tomcat:
    uriEncoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://124.222.125.175:3306/trackpack?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: NewPassword@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # ????
      minimum-idle: 5  # ???????
      maximum-pool-size: 20  # ?????
      idle-timeout: 600000  # ???????? (10??)
      max-lifetime: 1800000  # ?????? (30??)
      connection-timeout: 30000  # ???????? (30?)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.qq.com #???QQ?????????? SMTP ?????, ????, ???????????, ??(????, ????)???: smtp.xxx.com?????
    port: 587
    username: 2044978721@qq.com #qq??
    password: pajdcdkinctsbchd #qq?????
    protocol: smtp #??????
    properties.mail.smtp.auth: true   #????????????true,?????????????
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: false #??SSL ???????
    default-encoding: utf-8
  jackson:
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      database: 0
      host: 124.222.125.175
      port: 6379
      timeout: 1000
      password: a13738780767
#  jmx:
#    enabled: true
#    default-domain: your.domain.name

mybatis-plus:
  global-config:
    db-config:
      #????????NULL??
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  level:
#    org.hibernate.SQL: INFO  # ?? SQL ??
#    org.hibernate.type.descriptor.sql.BasicBinder: OFF  # ????????

logback:
  dir: logs
  #????
  filename:
    all: springboot-base-frame-all
    info: springboot-base-frame-info
    warn: springboot-base-frame-warn
    error: springboot-base-frame-error
  #???????
  maxhistory: 10
  #?????????
  maxfilesize: 100MB
  #????
  level: debug
  #??????
  charset: UTF-8
  #????
  CONSOLE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} %boldYellow([%thread]) %highlight(%-5level) %boldGreen(%logger{50}) - %msg%n'
  FILE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'